import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';

import { cn } from '../../lib/cn.js';
import { localePath } from '../../lib/links.js';

/**
 * Real colours sampled from the client's supplied roundel
 * (public/brand/craftdyne-logo.png) by scripts/generate-assets.mjs — see that
 * file's header comment for why the icon is drawn as a true circle rather than
 * cropped from the source PNG (the source's two caps have a genuine gap where
 * the wordmark sits and do not form a circle on their own).
 *
 * Used only on dark backgrounds (`tone="light"`, e.g. the site footer): the
 * client's real PNG has the wordmark and tagline set in navy, which is
 * illegible on a navy background, so that context falls back to this
 * synthesized icon plus live white text instead of the real image.
 *
 * Kept as constants here, rather than fetched from the generated SVG, so this
 * costs no extra request. If the client ever supplies an updated logo, re-run
 * `npm run assets` and copy its printed colour values into these four
 * constants.
 */
const ICON_GREEN_TOP = '#047a3a';
const ICON_GREEN_BOTTOM = '#07ba57';
const ICON_NAVY_TOP = '#073593';
const ICON_NAVY_BOTTOM = '#172951';

function SyntheticIcon({ className }) {
  return (
    <svg viewBox="0 0 40 40" aria-hidden="true" className={className}>
      <defs>
        <linearGradient id="cd-top" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={ICON_GREEN_TOP} />
          <stop offset="100%" stopColor={ICON_GREEN_BOTTOM} />
        </linearGradient>
        <linearGradient id="cd-bottom" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={ICON_NAVY_TOP} />
          <stop offset="100%" stopColor={ICON_NAVY_BOTTOM} />
        </linearGradient>
        <radialGradient id="cd-gloss" cx="35%" cy="20%" r="70%">
          <stop offset="0%" stopColor="#fff" stopOpacity="0.45" />
          <stop offset="55%" stopColor="#fff" stopOpacity="0" />
        </radialGradient>
        {/* Clips the top-half path to the true circle radius — without this,
            a path drawn even 1px inside the circle's diameter leaves a rim of
            the navy fill visible around the green half's curved edge. */}
        <clipPath id="cd-disc">
          <circle cx="20" cy="20" r="20" />
        </clipPath>
      </defs>
      <g clipPath="url(#cd-disc)">
        <circle cx="20" cy="20" r="20" fill="url(#cd-bottom)" />
        <path d="M0 20A20 20 0 0 1 40 20Z" fill="url(#cd-top)" />
        <circle cx="20" cy="20" r="20" fill="url(#cd-gloss)" />
      </g>
    </svg>
  );
}

export function BrandMark({
  lang,
  className,
  tone = 'dark',
  showTagline = true,
  taglineClassName = 'hidden sm:block',
}) {
  const { t } = useTranslation();
  const light = tone === 'light';
  const label = `${t('brand.name')} — ${t('brand.tagline')}`;

  if (light) {
    // Dark background (footer): the client's real artwork is unusable here
    // (navy text on navy), so this stays the colour-accurate synthesized icon
    // plus live, translated text.
    return (
      <Link
        to={localePath(lang)}
        // min-h-11 keeps the logo a compliant 44px tap target; without it the
        // 36px icon sets the height and the most-tapped link on the site is
        // under the minimum.
        className={cn('group inline-flex min-h-11 items-center gap-2.5 rounded-lg py-1', className)}
        aria-label={label}
      >
        <SyntheticIcon className="h-9 w-9 shrink-0 sm:h-10 sm:w-10" />
        <span className="flex min-w-0 flex-col leading-none">
          <span className="font-display text-lg font-extrabold tracking-tight text-white sm:text-xl">CraftDyne</span>
          {showTagline ? (
            <span className={cn('mt-1 text-[0.6875rem] font-medium tracking-wide text-white/70', taglineClassName)}>
              {t('brand.tagline')}
            </span>
          ) : null}
        </span>
      </Link>
    );
  }

  // Light background: use the client's real logo file directly, not a
  // recreation. Two crops are generated by scripts/generate-assets.mjs —
  // `showTagline` picks between them, matching this component's existing prop
  // contract rather than adding a separate one.
  const asset = showTagline
    ? { src: '/brand/craftdyne-logo-full.png', width: 708, height: 463 }
    : { src: '/brand/craftdyne-logo-icon-wordmark.png', width: 553, height: 372 };

  return (
    <Link
      to={localePath(lang)}
      className={cn('group inline-flex min-h-11 items-center rounded-lg', className)}
      aria-label={label}
    >
      {/*
        Sized in real pixels via `width`/`height` (prevents layout shift while
        the image loads) and displayed via the `h-*` classes below (controls
        the actual on-page size); `w-auto` lets the browser derive width from
        that height using the intrinsic aspect ratio, so the crop is never
        stretched.

        The height steps up across breakpoints rather than using a single fluid
        size, matching the header's own step pattern (see header.jsx) — at the
        client's request the logo is shown at a size where the tagline baked
        into the image is actually legible, not shrunk to fit a compact bar.
      */}
      <img
        src={asset.src}
        width={asset.width}
        height={asset.height}
        alt={label}
        className="h-16 w-auto sm:h-20 lg:h-24"
      />
    </Link>
  );
}
